### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by yrmt** [macaron-contrib/oauth2#2]
Hello, I am trying to package macaron-contrib/oauth2 but it does not build:

env GOPATH=/pkgsrc-work/obj/wip/go-macaron-contrib-oauth2/work:/usr/pkg/gopkg go install -v github.com/macaron-contrib/oauth2/...
github.com/macaron-contrib/oauth2/jws
github.com/macaron-contrib/oauth2/google
github.com/macaron-contrib/oauth2
# github.com/macaron-contrib/oauth2/google
/pkgsrc-work/obj/wip/go-macaron-contrib-oauth2/work/src/github.com/macaron-contrib/oauth2/google/appenginevm.go:42: undefined: oauth2.Option
/pkgsrc-work/obj/wip/go-macaron-contrib-oauth2/work/src/github.com/macaron-contrib/oauth2/google/appenginevm.go:42: undefined: appengine.Context
/pkgsrc-work/obj/wip/go-macaron-contrib-oauth2/work/src/github.com/macaron-contrib/oauth2/google/appenginevm.go:52: undefined: appengine.Context
/pkgsrc-work/obj/wip/go-macaron-contrib-oauth2/work/src/github.com/macaron-contrib/oauth2/google/appenginevm.go:52: undefined: oauth2.Options
/pkgsrc-work/obj/wip/go-macaron-contrib-oauth2/work/src/github.com/macaron-contrib/oauth2/google/appenginevm.go:97: undefined: appengine.Context
/pkgsrc-work/obj/wip/go-macaron-contrib-oauth2/work/src/github.com/macaron-contrib/oauth2/google/appenginevm.go:101: undefined: appengine.Context
/pkgsrc-work/obj/wip/go-macaron-contrib-oauth2/work/src/github.com/macaron-contrib/oauth2/google/appenginevm.go:106: undefined: appengine.Context
/pkgsrc-work/obj/wip/go-macaron-contrib-oauth2/work/src/github.com/macaron-contrib/oauth2/google/appenginevm.go:107: undefined: appengine.Context
/pkgsrc-work/obj/wip/go-macaron-contrib-oauth2/work/src/github.com/macaron-contrib/oauth2/google/google.go:41: undefined: oauth2.Option
/pkgsrc-work/obj/wip/go-macaron-contrib-oauth2/work/src/github.com/macaron-contrib/oauth2/google/google.go:49: undefined: oauth2.Option
/pkgsrc-work/obj/wip/go-macaron-contrib-oauth2/work/src/github.com/macaron-contrib/oauth2/google/google.go:49: too many errors

**Comment by Unknwon** [comment]
Hi, the `github.com/macaron-contrib/oauth2/google` package should only be used in GAE environment I believe, normal build should fail. :beer:

Just build the `github.com/macaron-contrib/oauth2` one is good to go.

**Comment by Unknwon** [comment]
The directory has been completely removed.
