### ISSUE TITLE
qq登录出错

### ISSUE THREAD

**Issue by nyrf** [macaron-contrib/oauth2#3]
因为qq返回的不是标准的json, 而是返回的 callback(xxx:xxx) 或者access_token=xxx&.......这类，看样子要特殊处理？

**Comment by Unknwon** [comment]
这个包其实挺坑的，只支持腾讯微博。。

**Comment by nyrf** [comment]
腾讯的返回值和别人不一样，是html的，而且格式也不一样，看来只能针对qq这去特殊处理了，谢谢

**Comment by Unknwon** [comment]
:smile:
